---
# ________       ______           ____  __
# ___  __ \___  ____  /_____________  |/ /
# __  /_/ /  / / /_  /__  ___/  _ \_    / 
# _  ____// /_/ /_  / _(__  )/  __/    |  
# /_/     \__,_/ /_/  /____/ \___//_/|_|  
#
# PulseX - Essentials for MCPE Server Software
# PulseAuth 1.0dev Config

hash:
 #Password Hashing Algorithm will be used
 #Default: sha1 [sha1/md5/sha256]
 algorithm: "sha1"
 #Extra data will be added while hashing
 extras: "{PASSWORD}"
 
database:
 #Set the database type will be used
 #Default: MySQL [MySQL/YAML]
 type: YAML
 #If MySQL is selected in "database", th
 mysql-databse:
     host: localhost
     port: 3306
     databse: pulseauth
     user: pulseauth
     password:

messages:
 #Message will be sent when a registered player joined
 registered: "This server uses PulseAuth\nType in your password to login"
 #Message will be sent when a player joined
 not-registered: "This server uses PulseAuth\nType in your password to register"
 #Message will be sent when a player logged in
 login: "Welcome back!"
 #Message will be sent when a player completed registration
 register: "Welcome to MCPE Server!"
...