---
# ________       ______           ____  __
# ___  __ \___  ____  /_____________  |/ /
# __  /_/ /  / / /_  /__  ___/  _ \_    / 
# _  ____// /_/ /_  / _(__  )/  __/    |  
# /_/     \__,_/ /_/  /____/ \___//_/|_|  
#
# PulseX - Essentials for MCPE Server Software
# PulseChat 1.0dev Config

spam:
advertise:
...