---
#  ____  _                                    _    
# |  _ \| |_   _  __ _ _____      _____  _ __| | __
# | |_) | | | | |/ _` / __\ \ /\ / / _ \| '__| |/ /
# |  __/| | |_| | (_| \__ \\ V  V / (_) | |  |   < 
# |_|   |_|\__,_|\__, |___/ \_/\_/ \___/|_|  |_|\_\
#                |___/                             
# Plugswork - Extends your MCPE Server beyond your imagination!
# Licensed under GNU Lesser General Public License (https://github.com/deotern/Plugswork/blob/master/LICENSE)
# Version: 1.php

#Global database will be used and accessed by Plugswork Module.
database:
    #Set the type of the database provider used
    #Default: sqlite [sqlite/mysql]
    provider: sqlite
    mysql-settings:
        host: localhost
        username: plugswork
        password: ********
        database: plugswork
        
#Enable or disable Plugswork Module.
#Default: true [true/false]
#If enabled, you're able adjust the settings of the module to your flavor with specific config.yml.
module:
    auth: true
    chat: true
    economy: true
...